base/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.index, name='home'),
    path('login', views.signin, name="login"),
    path('logout', views.signout, name="logout"),
    path('register', views.register, name="register"),
    path('playlist/<int:course_id>', views.playlist, name="playlist"),
    path('playlist', views.playlist, name="playlist2"),
    path('save_course', views.save_course, name='save_course'),
    path('video/<int:id>', views.watch_video, name="watch-video"),
    path('delete_comment/<int:id>', views.delete_comment, name="delete_comment"),
    path('like_video/<int:id>', views.like_video, name="like_video"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('courses', views.courses, name="courses"),
    path('tutors', views.tutors, name="tutors"),
    path('profile', views.profile, name="profile"),
    path('teacher/<int:id>', views.teacher_profile, name="teacher_profile"),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('liked_videos/', views.liked_videos, name='liked_videos'),
    path('user_comments/', views.user_comments, name='user_comments'),
    path('tutor/dashboard/', views.tutor_dashboard, name='tutor_dashboard'),
    path('tutor/courses/add/', views.add_course, name='add_course'),
    path('tutor/courses/', views.my_courses, name='my_courses'),
    path('tutor/courses/<int:course_id>/edit/', views.edit_course, name='edit_course'),
    path('tutor/courses/<int:course_id>/delete/', views.delete_course, name='delete_course'),
    path('tutor/students/', views.students_list, name='students_list'),
    path('tutor/analytics/', views.analytics, name='analytics'),
    path('tutor/student/<int:student_id>/course/<int:course_id>/', 
         views.student_progress, name='student_progress'),
]

innovatech/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('saved_playlists/', views.saved_playlists, name='saved_playlists'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

from email.policy import default
from random import choices
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator, FileExtensionValidator
import random


# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """
    Model representing a User.

    Attributes:
        id (Integer): The primary key and unique identifier of the user.
        email (String): The email of the user.
        phone_number (String): The phone number of the user.
        first_name (String): The first name of the user.
        last_name (String): The last name of the user.
        password (String): The password of the user.
        user_role (String): The role of the user.
        totalPoints (Integer): The total achievement points of the user.
        canShare (Boolean): Whether the user can share his sharecode or not.
        created_at (DateTime): The date and time when the user was created.
    """
    username = None
    USERNAME_FIELD = 'email'
    email = models.EmailField(_('email address'), unique=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    REQUIRED_FIELDS = []      
    created_at = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_set',
        blank=True,
        help_text=_(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
        verbose_name=_('groups'),
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_set',
        blank=True,
        help_text=_('Specific permissions for this user.'),
        verbose_name=_('user permissions'),
    )


class Student(models.Model):
    """
    Model representing a student.

    Attributes:
        user (OneToOneField): The user associated with the student.
        level (CharField): The education level of the student.
        country (CharField): The country of residence of the student.
        created_at (DateField): The date when the student record was created.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile_pics", default="profile_pics/Default_pfp.svg") # Should also change this to imagefield
    profile_views = models.IntegerField(validators=[MaxValueValidator(100)], default=0)
    bio = models.TextField(blank=True, null=True)
    preferred_name = models.CharField(max_length=20, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    enrolled_courses = models.ManyToManyField('Course', related_name='enrolled_students')
    liked_videos = models.ManyToManyField('CourseMaterial')
    saved_courses = models.ManyToManyField('Course', related_name='saved_students')
    created_at = models.DateField(auto_now_add=True)
    socials = models.OneToOneField('Socials', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.user.first_name
    
class Socials(models.Model):
    github = models.URLField(max_length=200,blank=True, null=True)
    instagram = models.URLField(max_length=200, blank=True, null=True)
    linkedin = models.URLField(max_length=200, blank=True, null=True)
    facebook = models.URLField(max_length=200, blank=True, null=True)
    twitter = models.URLField(max_length=200, blank=True, null=True) 
    number = models.CharField(max_length=20, blank=True, null=True)


class Tutor(models.Model):
    """
    Model representing a tutor.

    Attributes:
        user (OneToOneField): The user associated with the tutor.
        level (CharField): The education level of the tutor.
        subject (CharField): The subject taught by the tutor.
        verified (BooleanField): Indicates whether the tutor is verified.
        created_at (DateField): The date when the tutor record was created.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile_pics", default="https://upload.wikimedia.org/wikipedia/commons/2/2c/Default_pfp.svg") # Should also change this to imagefield
    subject = models.CharField(max_length=100)
    verified = models.BooleanField(default=False)
    rating = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(5)])
    likes = models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        if self.user.is_superuser:
            return "Admin"
        return self.user.first_name + " " + self.user.last_name

class Course(models.Model):
    """
    Model representing a course.

    Attributes:
        course_name (CharField): The name of the course.
        course_description (TextField): The description of the course.
        time_to_complete (CharField): The estimated time to complete the course.
        price (DecimalField): The price of the course.
        created_at (DateField): The date when the course record was created.
    """
    course_name = models.CharField(max_length=100)
    course_image = models.TextField()
    course_description = models.TextField()
    course_category = models.TextField(blank=True, null=True)
    course_tutor = models.ForeignKey(Tutor, on_delete=models.SET_DEFAULT, default=1)
    time_to_complete = models.CharField(max_length=100)
    price = models.DecimalField(blank=True, validators=[MinValueValidator(0)], decimal_places=2, max_digits=10, default=0.0)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.course_name


class CourseMaterial(models.Model):
    """
    Model representing course materials for a course week.

    Attributes:
        week (ForeignKey): The week associated with the material.
        material_type (CharField): The type of material (text or video).
        text (TextField): The text content (if material_type is text).
        video (FileField): The video file (if material_type is video).
    """
    TEXT = 'text'
    VIDEO = 'video'
    MATERIAL_TYPE_CHOICES = [
        (TEXT, 'Text'),
        (VIDEO, 'Video'),
    ]

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="materials")
    thumbnail = models.TextField(default="https://www.myutilitygenius.co.uk/assets/images/blogs/default-image.jpg")
    title = models.CharField(max_length=200)
    likes = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)
    time_to_complete = models.IntegerField(blank=True, null=True)
    video = models.FileField(upload_to='videos_uploaded', null=True, blank=True,
                             validators=[FileExtensionValidator(
                                 allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])
    

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class VideoComment(models.Model):
    """
    Represents a comment on a course.

    Attributes:
        course (Course): The course on which the comment is made.
        user (User): The user who made the comment.
        comment (str): The text of the comment.
        added_at (DateTime): The date and time when the comment was added.
    """
    course_material = models.ForeignKey(CourseMaterial, on_delete=models.CASCADE, related_name="comments")
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    added_at = models.DateTimeField(auto_now=True)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Innovatech CodingHub's aim is perfectly aligned with the professionalism and we would value your skills in this area of expertise."
    />
    <meta name="keywords" content="HTML, CSS and JavaScript" />
    <meta name="An Author" content="Innovatech CodingHub" />
    <title>{% block title %}My Site{% endblock %}</title>
    <!--Favicon-->
    <link rel="shortcut icon" href={% static "images/INNOVATECH CODINGHUB.jpg"
    %} type="image/x-icon">
    <!-- font awesome cdn link  -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
    />
    <!-- custom css file link  -->
    <link rel="stylesheet" href={% static "css/style.css" %} />
  </head>
  <body>
    <header class="header">
      <section class="flex">
        <a href="{% url 'home' %}" class="logo" class="icons"
          ><img src={% static "images/INNOVATECH CODINGHUB.jpg" %}
          class="logo-image" alt=""></a
        >

        <form action="search.html" method="post" class="search-form">
          <input
            type="text"
            name="search_box"
            required
            placeholder="search courses..."
            maxlength="100"
          />
          <button type="submit" class="fas fa-search"></button>
        </form>

        <div class="icons">
          <div id="menu-btn" class="fas fa-bars"></div>
          <div id="search-btn" class="fas fa-search"></div>
          <div id="user-btn" class="fas fa-user"></div>
          <div id="toggle-btn" class="fas fa-sun"></div>
        </div>

        <div class="profile">
          <img src={% static "images/Keys.png" %} class="image" alt="">
          <h3 class="name">{{student.user.first_name}} {{student.user.last_name}}</h3>
          <p class="role">learner</p>
          <a href="{% url "profile" %}" class="btn">view profile</a>
          <div class="flex-btn">
            {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="option-btn">logout</a>
            {% else %}
              <a href="{% url 'login' %}" class="option-btn">login</a>
              <a href="./register_Aluel.html" class="option-btn">register</a>
            {% endif %}
          </div>
        </div>
      </section>
    </header>

    <div class="side-bar">
      <div id="close-btn">
        <i class="fas fa-times"></i>
      </div>

      <div class="profile">
        <img src={% static "images/Keys.png" %} class="image" alt="">
        <h3 class="name">{{student.user.first_name}} {{student.user.last_name}}</h3>
        <p class="role">learner</p>
        <a href="{% url "profile" %}" class="btn">view profile</a>
      </div>

      <nav class="navbar">
        <a href="{% url 'home' %}"
          ><i class="fas fa-home"></i><span>Home</span></a
        >
        <a href="{% url "about" %}"
          ><i class="fas fa-question"></i><span>About Us</span></a
        >
        <a href="{% url "courses" %}"
          ><i class="fas fa-graduation-cap"></i><span>Courses</span></a
        >
        <a href="{% url "tutors" %}"
          ><i class="fas fa-chalkboard-user"></i><span>Tutors</span></a
        >
        <a href="{% url "contact" %}"
          ><i class="fas fa-headset"></i><span>Contact us</span></a
        >
      </nav>
    </div>

    {% block content %} {% endblock %}

    <script src={% static "js/script.js" %}></script>

  </body>
</html>

templates/contact.html
{% extends 'base.html' %} {% load static %} {% block title %}Contact{% endblock %}
{% block content %}
    <section class="contact">
      <div class="row">
        <div class="image">
          <img src={% static "images/istockphoto-1530025047-612x612.jpg" %}
          alt="">
        </div>

        <form action="" method="post">
          <h3>get in touch</h3>
          <input
            type="text"
            placeholder="enter your name"
            name="name"
            required
            maxlength="50"
            class="box"
            aria-required="true"
          />
          <input
            type="email"
            placeholder="enter your email"
            name="email"
            required
            maxlength="50"
            class="box"
            aria-required="true"
          />
          <input
            type="number"
            placeholder="enter your number"
            name="number"
            required
            maxlength="50"
            class="box"
            aria-required="true"
          />
          <textarea
            name="msg"
            class="box"
            placeholder="enter your message"
            required
            maxlength="1000"
            cols="30"
            rows="10"
            aria-required="true"
          ></textarea>
          <input
            type="submit"
            value="send message"
            class="inline-btn"
            name="submit"
          />
        </form>
      </div>

      <div class="box-container">
        <div class="box">
          <i class="fas fa-phone"></i>
          <h3>phone number</h3>
          <a href="tel: +250798619967">+250-798-619-967</a>
          <a href="tel: +211927319931">+211-927-319-931</a>
        </div>

        <div class="box">
          <i class="fas fa-envelope"></i>
          <h3>email address</h3>
          <a href="mailto:shaikhanas@gmail.com">g.pawuoi@alustudent.com</a>
          <a href="mailto:anasbhai@gmail.com">innovatechcodinghub@gmail.com</a>
        </div>

        <div class="box">
          <i class="fas fa-map-marker-alt"></i>
          <h3>office address</h3>
          <a href="#"
            >flat no. 1, a-1 building, Thongpieng, Juba, South Sudan</a
          >
        </div>
      </div>
    </section>
{% endblock %}

templates/courses.html
{% extends 'base.html' %} {% load static %} {% block title %}Courses{% endblock %}
{% block content %}
    <section class="courses">
      <h1 class="heading">Our Courses</h1>

      <div class="box-container">
        {% for course in courses %}
        <div class="box">
          <div class="tutor">
            <img src="{{course.course_tutor.profile_pic}}" alt="" />
            <div class="info">
              <h3>{{course.course_tutor}}</h3>
              <span>{{course.created_at}}</span>
            </div>
          </div>
          <div class="thumb">
            <img src="{{course.course_image}}" alt="" />
            <span>{{course.materials.all|length}} Videos</span>
          </div>
          <h3 class="title">{{course.course_name}}</h3>
          <a href="{% url 'playlist' course.id %}" class="inline-btn">view playlist</a>
        </div>
        {% endfor %}
    
      </div>
    </section>
{% endblock %}

templates/home.html
{% extends 'base.html' %} {% load static %} {% block title %}Home{% endblock %}
{% block content %}
<section class="home-grid">
  <h1 class="heading">quick options</h1>

  <div class="box-container">
    <div class="box">
      <h3 class="title">likes and comments</h3>
      <p class="likes">total likes : <span>{{student.liked_videos.all|length}}</span></p>
      <a href="#" class="inline-btn">view likes</a>
      <p class="likes">
        total comments : <span>{{student.comments.all|length}}</span>
      </p>
      <a href="#" class="inline-btn">view comments</a>
      <p class="likes">
        saved playlists : <span>{{student.saved_courses|length}}</span>
      </p>
      <a href="#" class="inline-btn">view playlists</a>
    </div>

    <div class="box">
      <h3 class="title">top categories</h3>
      <div class="flex">
        <a href="#"
          ><i class="fas fa-code"></i><span>Development Courses</span></a
        >
        <a href="#"><i class="fas fa-pen"></i><span>UI/UX Design</span></a>
        <a href="#"><i class="fas fa-camera"></i><span>Photography</span></a>
        <a href="#"><i class="fas fa-cog"></i><span>Software</span></a>
        <a href="#"><i class="fas fa-cog"></i><span>Data Analysis</span></a>
      </div>
    </div>

    <div class="box">
      <h3 class="title">popular topics</h3>
      <div class="flex">
        <a href="#"><i class="fab fa-html5"></i><span>HTML</span></a>
        <a href="#"><i class="fab fa-css3"></i><span>CSS</span></a>
        <a href="#"><i class="fab fa-js"></i><span>Javascript</span></a>
        <a href="#"><i class="fab fa-react"></i><span>React</span></a>
        <a href="#"><i class="fab fa-php"></i><span>PHP</span></a>
        <a href="#"><i class="fab fa-bootstrap"></i><span>Bootstrap</span></a>
      </div>
    </div>

    <div class="box">
      <h3 class="title">
        Are you interested to become a tutor at Innovatech CodingHub?
      </h3>
      <p class="tutor">
        Innovatech CodingHub's aim is perfectly aligned with the professionalism
        and we would value your skills in this area of expertise.
      </p>
      <a href="./register.html" class="inline-btn">get started</a>
    </div>
  </div>
</section>
<section class="courses">
  <h1 class="heading">Innovatech CodingHub courses</h1>

  <div class="box-container">
    {% for course in courses %}
    <div class="box">
      <div class="tutor">
        <img src="{{course.course_tutor.profile_pic}}" alt="" />
        <div class="info">
          <h3>{{course.course_tutor}}</h3>
          <span>{{course.created_at}}</span>
        </div>
      </div>
      <div class="thumb">
        <img src="{{course.course_image}}" alt="" />
        <span>{{course.materials.all|length}} Videos</span>
      </div>
      <h3 class="title">{{course.course_name}}</h3>
      <a href="{% url 'playlist' course.id %}" class="inline-btn">view playlist</a>
    </div>
    {% endfor %}

  </div>

  <div class="more-btn">
    <a href="courses.html" class="inline-option-btn">view all courses</a>
  </div>
</section>
{% endblock %}

templates/liked_videos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Liked Videos{% endblock %}
{% block content %}
<section class="playlist-videos">
    <h1 class="heading">Liked Videos</h1>

    {% if liked_videos %}
        <div class="box-container">
            {% for video in liked_videos %}
            <div class="box">
                <div class="tutor">
                    <div>
                        <h3>{{ video.course.course_tutor }}</h3>
                        <span>{{ video.created_at|date:"F d, Y" }}</span>
                    </div>
                </div>
                <a href="{% url 'watch-video' video.id %}" class="video-link">
                    <div class="thumb">
                        <img src="{{ video.thumbnail }}" alt="">
                        <i class="fas fa-play" style="margin-top: 40px;"></i>
                    </div>
                    <h3 class="title">{{ video.title }}</h3>
                </a>
                <div class="flex-btn">
                    <form action="" method="post" class="like-form">
                        <button type="button" onclick='like_video(this, "{% url 'like_video' video.id %}")' class="like-btn liked">
                            <span>Liked</span>
                        </button>
                        {% csrf_token %}
                    </form>
                    <a href="{% url 'playlist' video.course.id %}" class="inline-btn">view playlist</a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="empty">
            <p>No liked videos found!</p>
            <a href="{% url 'courses' %}" class="inline-btn">browse courses</a>
        </div>
    {% endif %}
</section>
{% endblock %} 

templates/login.html
{% extends 'base.html' %}

{% load static %} {% block title %}Log In{% endblock %} {% block content %}
<section class="form-container">
  <form action="{% url 'login' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>login now</h3>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li class="message message-{{ message.tags }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <p>your email <span>*</span></p>
    <input
      type="email"
      name="email"
      placeholder="enter your email"
      required
      maxlength="50"
      class="box"
    />
    <p>your password <span>*</span></p>
    <input
      type="password"
      name="password"
      placeholder="enter your password"
      required
      maxlength="20"
      class="box"
    />
    <input type="submit" value="login new" name="submit" class="btn" />
  </form>
</section>
{% endblock %}

templates/playlist.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Playlist{% endblock %}
{% block content %}
<section class="playlist-details">
    <h1 class="heading">Playlist Details</h1>

    <div class="row">
        <div class="column">
            <form action="" method="post" class="save-playlist">
                {% if course in student.saved_courses.all %}
                <button type="button" onclick='save_course(this, "{% url 'save_course' %}", "{{student.id}}", "{{course.id}}")' name="save_list">
                  <i class="far fa-bookmark"></i> <span>Saved</span>
                {% csrf_token %}
                </button>
                {% else %}
                <button type="button" onclick='save_course(this, "{% url 'save_course' %}", "{{student.id}}", "{{course.id}}")' name="save_list">
                  <i class="far fa-bookmark"></i> <span>Save Playlist</span>
                {% csrf_token %}
                </button>
                {% endif %}
                </form>

            <div class="thumb">
                <img src="{{playlist.0.course.course_image}}" alt="" />
                <span>{{ playlist|length }} videos</span>
            </div>
        </div>
        <div class="column">
            <div class="tutor">
                <img src="{{ user.student.profile_pic.url }}" alt="">
                <div>
                    <h3>{{ user.first_name }} {{ user.last_name }}</h3>
                    <span>{{ playlist.0.course.created_at}}</span>
                </div>
            </div>

            <div class="details">
                <h3>{{playlist.0.course.course_name}}</h3>
                <p>
                    {{playlist.0.course.course_description}}
                </p>
                <a href="teacher_profile.html" class="inline-btn">View Profile</a>
            </div>
        </div>
    </div>
</section>

<section class="playlist-videos">
    <h1 class="heading">Playlist Videos</h1>

    <div class="box-container">
        {% for video in playlist %}
        <a class="box" href="{% url 'watch-video' video.id %}">
            <i class="fas fa-play"></i>
            <img src="{{ video.thumbnail }}" alt="{{ video.title }}" />
            <h3>{{ video.title }}</h3>
        </a>
        {% endfor %}
    </div>
</section>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
<section class="form-container">
  <form
    action="{% url 'register' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <h3>register now</h3>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li class="message message-{{ message.tags }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    <p>your name <span>*</span></p>
    <input
      type="text"
      name="name"
      placeholder="enter your name"
      required
      maxlength="50"
      class="box"
    />
    <p>your email <span>*</span></p>
    <input
      type="email"
      name="email"
      placeholder="enter your email"
      required
      maxlength="50"
      class="box"
    />
    <p>your password <span>*</span></p>
    <input
      type="password"
      name="ps1"
      placeholder="enter your password"
      required
      maxlength="20"
      class="box"
    />
    <p>confirm password <span>*</span></p>
    <input
      type="password"
      name="ps2"
      placeholder="confirm your password"
      required
      maxlength="20"
      class="box"
    />
    <p>select profile</p>
    <input type="file" name="profile_pic" accept="image/*" class="box" />
    <input type="submit" value="register new" name="submit" class="btn" />
  </form>
</section>
{% endblock %}

templates/saved_playlists.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Saved Playlists{% endblock %}
{% block content %}
<section class="courses">
  <h1 class="heading">Saved Playlists</h1>

  {% if saved_courses %}
    <div class="box-container">
      {% for course in saved_courses %}
      <div class="box">
        <div class="tutor">
          <img src="{{course.course_tutor.profile_pic}}" alt="" />
          <div class="info">
            <h3>{{course.course_tutor}}</h3>
            <span>{{course.created_at}}</span>
          </div>
        </div>
        <div class="thumb">
          <img src="{{course.course_image}}" alt="" />
          <span>{{course.materials.all|length}} Videos</span>
        </div>
        <h3 class="title">{{course.course_name}}</h3>
        <form action="" method="post" class="save-playlist">
          <button type="button" onclick='save_course(this, "{% url 'save_course' %}", "{{student.id}}", "{{course.id}}")' name="save_list" class="saved">
            <i class="far fa-bookmark"></i> <span>Saved</span>
          {% csrf_token %}
          </button>
        </form>
        <a href="{% url 'playlist' course.id %}" class="inline-btn">view playlist</a>
      </div>
      {% endfor %}
    </div>
  {% else %}
    <div class="empty">
      <p>No saved playlists found!</p>
      <a href="{% url 'courses' %}" class="inline-btn">browse courses</a>
    </div>
  {% endif %}
</section>
{% endblock %} 

templates/teachers.html
{% extends 'base.html' %} {% load static %} {% block title %}Tutors{% endblock %}
{% block content %}
<section class="teachers">
  <h1 class="heading">expert teachers</h1>

  <form action="" method="get" class="search-tutor">
    <input
      type="text"
      name="search_box"
      placeholder="search tutors..."
      maxlength="100"
      value="{{ search_query }}"
    />
    <button type="submit" class="fas fa-search"></button>
  </form>

  <div class="box-container">
    <div class="box offer">
      <h3>Join Innovatech and become a tutor</h3>
      <p>
        Innovatech CodingHub's aim is perfectly aligned with the professionalism
        and we would value your skills in this area of expertise.
      </p>
      <a href="{% url 'register' %}" class="inline-btn">get started</a>
    </div>

    {% for tutor in tutors %}
    <div class="box">
      <div class="tutor">
        <img src={{tutor.profile_pic}} alt="">
        <div>
          <h3>{{tutor}}</h3>
          <span>{{tutor.subject}}</span>
        </div>
      </div>
      <p>total playlists : <span>{{tutor.course_set.all|length}}</span></p>
      <p>total videos : <span>{{tutor.video_count}}</span></p>
      <p>total likes : <span>{{tutor.like_count}}</span></p>
      <a href="{% url "teacher_profile" tutor.id %}" class="inline-btn">view profile</a>
    </div>
    {% endfor %}

  </div>
</section>
{% endblock %}